# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FieldStats
                                 A QGIS plugin
 This pluggins calculate basic stats and graph histogram and boxplot
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-06-07
        copyright            : (C) 2024 by Manuel Alejandro Montealegre Martínez
        email                : manuel.montealegre@udea.edu.co
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FieldStats class from file FieldStats.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .field_stats import FieldStats
    return FieldStats(iface)
